// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(admin)/(auth)/login/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(auth)/login/page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ../../src/app/(admin)/(dashboard)/bike-lists/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/bike-lists/page.js")
  handler satisfies AppPageConfig<"/bike-lists">
}

// Validate ../../src/app/(admin)/(dashboard)/bike-type-list/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/bike-type-list/page.js")
  handler satisfies AppPageConfig<"/bike-type-list">
}

// Validate ../../src/app/(admin)/(dashboard)/branch-management/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/branch-management/page.js")
  handler satisfies AppPageConfig<"/branch-management">
}

// Validate ../../src/app/(admin)/(dashboard)/discount-management/create/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/discount-management/create/page.js")
  handler satisfies AppPageConfig<"/discount-management/create">
}

// Validate ../../src/app/(admin)/(dashboard)/discount-management/edit/[id]/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/discount-management/edit/[id]/page.js")
  handler satisfies AppPageConfig<"/discount-management/edit/[id]">
}

// Validate ../../src/app/(admin)/(dashboard)/discount-management/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/discount-management/page.js")
  handler satisfies AppPageConfig<"/discount-management">
}

// Validate ../../src/app/(admin)/(dashboard)/history-bike-list/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/history-bike-list/page.js")
  handler satisfies AppPageConfig<"/history-bike-list">
}

// Validate ../../src/app/(admin)/(dashboard)/homepage/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/homepage/page.js")
  handler satisfies AppPageConfig<"/homepage">
}

// Validate ../../src/app/(admin)/(dashboard)/maintenance-bike-lists/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/maintenance-bike-lists/page.js")
  handler satisfies AppPageConfig<"/maintenance-bike-lists">
}

// Validate ../../src/app/(admin)/(dashboard)/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/(admin)/(dashboard)/rent-bike-list/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/rent-bike-list/page.js")
  handler satisfies AppPageConfig<"/rent-bike-list">
}

// Validate ../../src/app/(admin)/(dashboard)/test-auth/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/test-auth/page.js")
  handler satisfies AppPageConfig<"/test-auth">
}

// Validate ../../src/app/(admin)/(dashboard)/user-management/page.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/user-management/page.js")
  handler satisfies AppPageConfig<"/user-management">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}







// Validate ../../src/app/(admin)/(auth)/layout.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(auth)/layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ../../src/app/(admin)/(dashboard)/layout.tsx
{
  const handler = {} as typeof import("../../src/app/(admin)/(dashboard)/layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
